### ISSUE TITLE
'fiber-storage' outputs warning: Fiber#storage has borked keys and is being monkey-patched.

### ISSUE THREAD

**Issue by daipom** [socketry/fiber-local#4]
# Abstraction

From https://github.com/fluent/fluentd/issues/4488.

Looks like `fiber-local` uses `fiber-storage` from v1.1.0.
`fiber-storage` outputs the following warning message when `require`:

```
Fiber#storage has borked keys and is being monkey-patched.
```

`fiber-local` v1.0 does not output this warning because it does not use `fiber-storage`.

[Fluentd](https://github.com/fluent/fluentd) uses `console` gem, and `console` v1.25 uses `fiber-local` v1.1.
So, this warning message occurs every time when executing `Fluentd`.

Is this a bug of `fiber-storage` or `fiber-local`?
Or is there something wrong with the usage?

(I can't find `fiber-storage` GitHub repository: https://github.com/socketry/fiber-storage, so I have made this issue here.)

# How to reproduce

Ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
OS: Ubuntu 20.04

`fiber-storage`:

```console
$ gem install fiber-storage
$ gem list fiber-storage

*** LOCAL GEMS ***

fiber-storage (0.1.0)
$ ruby -e "require 'fiber/storage'"
Fiber#storage has borked keys and is being monkey-patched.
```

`fiber-local`:

```console
$ gem install fiber-local -v 1.1.0
$ gem list fiber-local

*** LOCAL GEMS ***

fiber-local (1.1.0)
$ ruby -e "require 'fiber/local'"
Fiber#storage has borked keys and is being monkey-patched.
$ gem uninstall fiber-local -v 1.1.0
$ gem install fiber-local -v 1.0.0
$ gem list fiber-local

*** LOCAL GEMS ***

fiber-local (1.0.0)
$ ruby -e "require 'fiber/local'"
(no warning)
```

`Fluentd`:

```console
$ git clone git@github.com:fluent/fluentd.git
$ cd fluentd
$ bundle
$ bundle exec gem list console

*** LOCAL GEMS ***

console (1.25.2)
$ bundle exec gem list fiber-local

*** LOCAL GEMS ***

fiber-local (1.1.0)
$ bundle exec fluentd --version
Fiber#storage has borked keys and is being monkey-patched.
fluentd 1.17.0
```

**Comment by daipom** [comment]
@ioquatix If you have time, could you please take a look at this?

**Comment by ioquatix** [comment]
Sorry, I missed this. I'll take a look. Maybe we don't need to emit such a warning.

**Comment by daipom** [comment]
Thanks! Let me know if there is anything I can help!

**Comment by ioquatix** [comment]
Okay, I've removed the warning.

**Comment by daipom** [comment]
Thanks! I have confirmed this issue is fixed!
Thanks so much for always responding so quickly!

**Comment by broksonic21** [comment]
confirmed this fixed things for us too. thanks!

**Comment by ioquatix** [comment]
Thanks for your confirmations!
